#!/usr/bin/env python3
"""Generate the rule tables and counts the documentation quotes, from the binary itself.

Rule counts used to be written by hand, and drifted: the site said 58 lint rules while the
binary had 66, and a runtime warning said 60. Anything countable now comes from
``vsg-rs --list_rules``, and CI fails when the committed output no longer matches.

    python scripts/gen_rule_docs.py            # rewrite the generated pages
    python scripts/gen_rule_docs.py --check    # fail if they are out of date

The output is committed, because Read the Docs builds the site with mkdocs alone and cannot
run cargo.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

# Native rules, by what the analyser knows when it reports them. The order is the order the
# reference lists them in; the text is the section's own explanation of its certainty.
CATEGORIES: list[tuple[str, str, tuple[str, ...]]] = [
    (
        "Resolved semantics",
        "Reported by the VHDL front end from a resolved symbol table: a name, its declaration "
        "and its type. These need a library map; see [Project setup](project-setup.md).",
        (),  # everything not listed below
    ),
    (
        "Dataflow and structure",
        "Reported by vsg-rs from the syntax tree plus the design's port connections. The "
        "evidence is structural, so these run without a library map.",
        (
            "lint_601",
            "lint_710",
            "lint_711",
            "lint_712",
            "lint_720",
            "lint_730",
            "lint_740",
            "lint_750",
        ),
    ),
    (
        "Experimental (off by default)",
        "These infer design intent that the source does not state outright, so they cannot point "
        "at the evidence the rules above can. `lint_700` is off unless you enable it; `lint_600` "
        "is on, because a latch is derived from the assignments themselves once a process is "
        "taken to be combinational.",
        ("lint_600", "lint_700"),
    ),
    (
        "Style policy",
        "A house's choice rather than a defect: what they report is legal and works today, and "
        "matters only because of what the project means to do with the code. Off unless "
        "configured.",
        ("lint_602", "lint_603", "lint_713", "lint_760"),
    ),
]

GENERATED = "<!-- Generated by scripts/gen_rule_docs.py. Do not edit by hand. -->"


def list_rules() -> list[tuple[str, str, str]]:
    """Every rule as (id, layer, description), from the binary."""
    binary = ROOT / "target" / "release" / "vsg-rs"
    if not binary.exists():
        subprocess.run(
            ["cargo", "build", "--release"], cwd=ROOT, check=True, stdout=subprocess.DEVNULL
        )
    out = subprocess.run(
        [str(binary), "--list_rules"], cwd=ROOT, check=True, capture_output=True, text=True
    ).stdout
    rules = []
    for line in out.splitlines():
        match = re.match(r"^(\S+)\s+(.*)$", line)
        if not match:
            continue
        rule, rest = match.group(1), match.group(2)
        if rest.startswith("lint (--check lint): "):
            rules.append((rule, "lint", rest[len("lint (--check lint): ") :]))
        else:
            rules.append((rule, "style", rest))
    return rules


def counts(rules: list[tuple[str, str, str]]) -> dict[str, int]:
    lint = [r for r in rules if r[1] == "lint"]
    named = {rule for _, _, group in CATEGORIES for rule in group}
    return {
        "vsg": len(rules) - len(lint),
        "lint": len(lint),
        "resolved": len([r for r in lint if r[0] not in named]),
        "native": len(named),
    }


def cli_reference() -> str:
    """The CLI page, from the binary's own --help, so the two cannot drift."""
    binary = ROOT / "target" / "release" / "vsg-rs"
    help_text = subprocess.run(
        [str(binary), "--help"], cwd=ROOT, check=True, capture_output=True, text=True
    ).stdout
    # clap prints `      --flag <VALUE>` then an indented description on the following lines.
    options: list[tuple[str, str]] = []
    flag = None
    description: list[str] = []
    for line in help_text.splitlines():
        if re.match(r"^  {0,2}-|^      --", line):
            if flag:
                options.append((flag, " ".join(description).strip()))
            flag, description = line.strip(), []
        elif line.startswith("          ") and flag:
            description.append(line.strip())
    if flag:
        options.append((flag, " ".join(description).strip()))

    vsg = [(f, d) for f, d in options if "(vsg-rs extension)" not in d]
    ours = [(f, d.replace(" (vsg-rs extension)", "")) for f, d in options if "(vsg-rs extension)" in d]

    def table(rows: list[tuple[str, str]]) -> list[str]:
        out = ["| Option | Meaning |", "|---|---|"]
        out += [f"| `{f}` | {d} |" for f, d in rows]
        return out + [""]

    return "\n".join(
        [
            GENERATED,
            "",
            "# CLI reference",
            "",
            "Generated from `vsg-rs --help`, so this page cannot drift from the binary.",
            "",
            "```text",
            "vsg-rs [OPTIONS] [FILENAME]...",
            "vsg-rs lint [OPTIONS] [FILENAME]...",
            "```",
            "",
            "`lint` is a subcommand only when it is the first argument and no file or directory of",
            "that name exists. Every VSG command line therefore keeps working unchanged; underneath,",
            "`lint` means `--check lint`.",
            "",
            "## VSG-compatible options",
            "",
            "These behave as VSG's do, and",
            "[VSG documents them](https://vhdl-style-guide.readthedocs.io/en/latest/usage.html).",
            "",
            *table(vsg),
            "## Options vsg-rs adds",
            "",
            *table(ours),
            "## Exit codes",
            "",
            "| Code | Meaning |",
            "|---|---|",
            "| 0 | nothing of error severity was reported |",
            "| 1 | an error-severity violation, a missing input file, or an invalid argument |",
            "",
            "Warnings alone do not fail a run. `--fail_on` narrows which layers count towards the",
            "exit code; waived violations never do.",
            "",
            "## Which files are checked",
            "",
            "Files are taken from `-f/--filename` and from positional arguments. `--recursive` adds",
            "the `.vhd` and `.vhdl` files in any directory given. `--stdin` reads one file from",
            "standard input and disables file selection; `--stdin_filename` gives that input a path",
            "for configuration lookup and reports.",
            "",
            "## Where configuration comes from",
            "",
            "1. `-c/--configuration`, merged in the order given.",
            "2. Otherwise `vsg-rs.yaml`, `.vsg-rs.yaml`, `vsg-rs.json` or `.vsg-rs.json`, searched",
            "   from the file's own directory upwards.",
            "3. `--lint_configuration` is merged on top for the lint layer only.",
            "",
            "The library map (`vhdl_ls.toml`) is read from the working directory; see",
            "[project setup](project-setup.md).",
            "",
        ]
    )


def rule_reference(rules: list[tuple[str, str, str]]) -> str:
    lint = {rule: description for rule, layer, description in rules if layer == "lint"}
    named = {rule for _, _, group in CATEGORIES for rule in group}
    out = [
        GENERATED,
        "",
        "# Rule reference",
        "",
        "Every rule of the lint layer, grouped by what the analyser knows when it reports one.",
        "`vsg-rs --explain <rule>` prints the same description, and `--list_rules` lists these",
        "alongside the VSG style rules.",
        "",
    ]
    for title, blurb, group in CATEGORIES:
        chosen = (
            sorted(rule for rule in lint if rule not in named)
            if not group
            else [rule for rule in group if rule in lint]
        )
        if not chosen:
            continue
        out += [f"## {title}", "", blurb, "", "| Rule | Reports |", "|---|---|"]
        out += [
            f"| [`{rule}`](native-rules.md#{rule}) | {lint[rule]} |"
            if rule in named
            else f"| `{rule}` | {lint[rule]} |"
            for rule in chosen
        ]
        out += [""]
    return "\n".join(out)


def counts_page(rules: list[tuple[str, str, str]]) -> str:
    n = counts(rules)
    return "\n".join(
        [
            GENERATED,
            "",
            "# Rule counts",
            "",
            "Quoted by other pages through a snippet, so no page states a number of its own.",
            "",
            "| Set | Rules |",
            "|---|---|",
            f"| VSG style rules | {n['vsg']} |",
            f"| Lint layer, total | {n['lint']} |",
            f"| — of those, resolved-semantic (need a library map) | {n['resolved']} |",
            f"| — of those, native to vsg-rs | {n['native']} |",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the pages are stale")
    args = parser.parse_args()

    rules = list_rules()
    pages = {
        DOCS / "rule-reference.md": rule_reference(rules),
        DOCS / "rule-counts.md": counts_page(rules),
        DOCS / "cli.md": cli_reference(),
    }
    stale = [p for p, text in pages.items() if not p.exists() or p.read_text() != text]
    if args.check:
        for page in stale:
            print(f"stale: {page.relative_to(ROOT)}", file=sys.stderr)
        if stale:
            print("run: python scripts/gen_rule_docs.py", file=sys.stderr)
        return 1 if stale else 0
    for page, text in pages.items():
        page.write_text(text)
        print(f"wrote {page.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
