//! VSG `case::keyword` rules and the reserved words each one controls (from the rule
//! descriptions of VSG 3.35). A rule applies to its keywords inside the construct its id names;
//! a keyword takes the case of the innermost such construct.

use vhdl_syntax::syntax::NodeKind as N;

use crate::rules::RuleInfo;

/// The constructs a keyword rule applies to, from its id prefix (`entity_010`: the `end` of
/// entities). Empty: everywhere. Subprogram bodies count as their specification's kind.
pub(crate) fn constructs(rule: &str) -> &'static [N] {
    use N::*;
    let prefix = rule.rsplit_once('_').map_or(rule, |(p, _)| p);
    match prefix {
        "after" => &[AfterClause],
        "alias_declaration" => &[AliasDeclaration],
        "architecture" => &[ArchitectureBody],
        "array_constraint" => &[IndexConstraint],
        "assert" => &[Assertion],
        "attribute_declaration" => &[AttributeDeclaration],
        "attribute_specification" => &[AttributeSpecification],
        "block" => &[BlockStatement],
        "case" => &[CaseStatement],
        "case_generate_alternative" => &[CaseGenerateAlternative],
        "case_generate_statement" => &[CaseGenerateStatement],
        "choice" => &[OthersChoice],
        "component" => &[ComponentDeclaration],
        "conditional_expressions" => &[ConditionalExpressions],
        "conditional_waveforms" => &[ConditionalWaveforms],
        "constant" => &[ConstantDeclaration],
        "constrained_array_definition" => &[ConstrainedArrayDefinition],
        "context" => &[ContextDeclaration],
        "context_ref" => &[ContextReference],
        "delay_mechanism" => &[InertialDelayMechanism, TransportDelayMechanism],
        "entity" => &[EntityDeclaration],
        "entity_specification" => &[EntitySpecification],
        "exit_statement" => &[ExitStatement],
        "external_constant_name" => &[ExternalConstantName],
        "external_signal_name" => &[ExternalSignalName],
        "external_variable_name" => &[ExternalVariableName],
        "file" => &[FileDeclaration],
        "file_open_information" => &[FileOpenInformation],
        "file_type_definition" => &[FileTypeDefinition],
        "for_generate_statement" => &[ForGenerateStatement],
        "function" => &[FunctionSpecification],
        "generate" => &[
            ForGenerateStatement,
            IfGenerateStatement,
            CaseGenerateStatement,
        ],
        "generic" => &[GenericClause],
        "generic_map" => &[GenericMapAspect],
        "if" => &[IfStatement],
        "if_generate_statement" => &[IfGenerateStatement],
        "index_subtype_definition" => &[IndexSubtypeDefinition],
        "instantiation" => &[ComponentInstantiationStatement],
        "interface_incomplete_type_declaration" => &[InterfaceIncompleteTypeDeclaration],
        "iteration_scheme" => &[ForScheme, WhileScheme],
        "library" => &[LibraryClause],
        "loop_statement" => &[LoopStatement],
        "next_statement" => &[NextStatement],
        "null_statement" => &[NullStatement],
        "package" => &[PackageDeclaration],
        "package_body" => &[PackageBody],
        "package_instantiation" => &[PackageInstantiationDeclaration],
        "parameter_specification" => &[ParameterSpecification],
        "port" => &[PortClause],
        "port_map" => &[PortMapAspect],
        "procedure" => &[ProcedureSpecification],
        "procedure_call" => &[ProcedureCallStatement],
        "process" => &[ProcessStatement],
        "protected_type" => &[ProtectedTypeDeclaration],
        "protected_type_body" => &[ProtectedTypeBody],
        "range" | "range_constraint" => &[RangeConstraint],
        "record_type_definition" => &[RecordTypeDefinition],
        "report_statement" => &[ReportStatement],
        "return_statement" => &[ReturnStatement],
        "selected_assignment" => &[
            ConcurrentSelectedSignalAssignment,
            SelectedWaveformAssignment,
            SelectedVariableAssignment,
            SelectedForceAssignment,
        ],
        "signal" => &[SignalDeclaration],
        "subprogram_instantiation" => &[SubprogramInstantiationDeclaration],
        "subtype" => &[SubtypeDeclaration],
        "type" => &[FullTypeDeclaration, IncompleteTypeDeclaration],
        "unbounded_array_definition" => &[UnboundedArrayDefinition],
        "use_clause" => &[UseClause],
        "variable" => &[VariableDeclaration],
        "wait" => &[WaitStatement],
        _ => &[],
    }
}

const fn info(id: &'static str) -> RuleInfo {
    RuleInfo::formatter(
        id,
        &["case", "case::keyword"],
        true,
        "Keyword case (applied by the formatter).",
    )
}

macro_rules! table {
    ($(($id:literal, &[$($word:literal),*]),)*) => {
        /// Each rule with the keywords it controls.
        pub(crate) static RULES: &[(RuleInfo, &[&str])] = &[$((info($id), &[$($word),*]),)*];
    };
}

table! {
    ("after_500", &["after"]),
    ("alias_declaration_500", &["alias"]),
    ("alias_declaration_501", &["is"]),
    ("architecture_004", &["architecture"]),
    ("architecture_009", &["end"]),
    ("architecture_019", &["of"]),
    ("architecture_020", &["is"]),
    ("architecture_021", &["begin"]),
    ("architecture_028", &["architecture"]),
    ("array_constraint_500", &["open"]),
    ("assert_500", &["assert"]),
    ("assert_501", &["report"]),
    ("assert_502", &["severity"]),
    ("attribute_declaration_500", &["attribute"]),
    ("attribute_specification_500", &["attribute"]),
    ("attribute_specification_502", &["of"]),
    ("attribute_specification_503", &["is"]),
    ("block_501", &["block"]),
    ("block_502", &["is"]),
    ("block_503", &["begin"]),
    ("block_504", &["end"]),
    ("block_505", &["block"]),
    ("case_014", &["case"]),
    ("case_015", &["is"]),
    ("case_016", &["when"]),
    ("case_017", &["end"]),
    ("case_018", &["case"]),
    ("case_generate_alternative_500", &["when"]),
    ("case_generate_statement_500", &["case"]),
    ("case_generate_statement_501", &["generate"]),
    ("choice_500", &["others"]),
    ("component_004", &["component"]),
    ("component_006", &["is"]),
    ("component_010", &["end"]),
    ("component_014", &["component"]),
    ("conditional_expressions_500", &["when"]),
    ("conditional_expressions_501", &["else"]),
    ("conditional_waveforms_500", &["when"]),
    ("conditional_waveforms_501", &["else"]),
    ("constant_002", &["constant"]),
    ("constrained_array_definition_500", &["array"]),
    ("constrained_array_definition_501", &["of"]),
    ("context_004", &["context"]),
    ("context_013", &["is"]),
    ("context_014", &["end"]),
    ("context_015", &["context"]),
    ("context_ref_003", &["context"]),
    ("delay_mechanism_500", &["transport"]),
    ("delay_mechanism_501", &["inertial"]),
    ("delay_mechanism_502", &["reject"]),
    ("entity_004", &["entity"]),
    ("entity_006", &["is"]),
    ("entity_010", &["end"]),
    ("entity_014", &["entity"]),
    ("entity_500", &["begin"]),
    ("entity_specification_500", &["others"]),
    ("entity_specification_501", &["all"]),
    ("exit_statement_500", &["exit"]),
    ("exit_statement_501", &["when"]),
    ("external_constant_name_500", &["constant"]),
    ("external_signal_name_500", &["signal"]),
    ("external_variable_name_500", &["variable"]),
    ("file_002", &["file"]),
    ("file_open_information_500", &["open"]),
    ("file_open_information_502", &["is"]),
    ("file_type_definition_500", &["file"]),
    ("file_type_definition_501", &["of"]),
    ("for_generate_statement_500", &["for"]),
    ("for_generate_statement_501", &["generate"]),
    ("function_004", &["begin"]),
    ("function_005", &["function"]),
    ("function_013", &["end"]),
    ("function_501", &["return"]),
    ("function_502", &["is"]),
    ("function_509", &["pure"]),
    ("function_510", &["in", "out", "inout", "buffer", "linkage"]),
    ("function_511", &["constant", "signal", "variable", "file"]),
    ("function_512", &["impure"]),
    ("generate_009", &["end"]),
    ("generate_010", &["generate"]),
    ("generate_500", &["begin"]),
    ("generate_501", &["end"]),
    ("generic_009", &["generic"]),
    ("generic_map_001", &["generic", "map"]),
    ("if_025", &["if"]),
    ("if_026", &["elsif"]),
    ("if_027", &["else"]),
    ("if_028", &["end"]),
    ("if_029", &["then"]),
    ("if_034", &["if"]),
    ("if_generate_statement_500", &["if"]),
    ("if_generate_statement_501", &["generate"]),
    ("if_generate_statement_502", &["elsif"]),
    ("if_generate_statement_503", &["else"]),
    ("index_subtype_definition_500", &["range"]),
    ("instantiation_027", &["entity"]),
    ("instantiation_031", &["component"]),
    ("interface_incomplete_type_declaration_500", &["type"]),
    ("iteration_scheme_500", &["while"]),
    ("iteration_scheme_501", &["for"]),
    ("library_004", &["library"]),
    ("library_005", &["use"]),
    ("logical_operator_500", &["and", "or", "nand", "nor", "xor", "xnor"]),
    ("loop_statement_500", &["loop"]),
    ("loop_statement_501", &["end"]),
    ("loop_statement_502", &["loop"]),
    ("next_statement_500", &["next"]),
    ("next_statement_501", &["when"]),
    ("null_statement_500", &["null"]),
    ("package_004", &["package"]),
    ("package_006", &["end"]),
    ("package_013", &["is"]),
    ("package_018", &["package"]),
    ("package_body_500", &["package"]),
    ("package_body_501", &["body"]),
    ("package_body_503", &["is"]),
    ("package_body_504", &["end"]),
    ("package_body_505", &["package"]),
    ("package_body_506", &["body"]),
    ("package_instantiation_500", &["package"]),
    ("package_instantiation_502", &["is"]),
    ("package_instantiation_503", &["new"]),
    ("parameter_specification_501", &["in"]),
    ("port_017", &["port"]),
    ("port_019", &["in", "out", "inout", "buffer", "linkage"]),
    ("port_map_001", &["port", "map"]),
    ("procedure_008", &["end"]),
    ("procedure_500", &["procedure"]),
    ("procedure_502", &["is"]),
    ("procedure_503", &["begin"]),
    ("procedure_504", &["end"]),
    ("procedure_510", &["in", "out", "inout", "buffer", "linkage"]),
    ("procedure_511", &["constant", "signal", "variable", "file"]),
    ("procedure_call_501", &["postponed"]),
    ("process_004", &["begin"]),
    ("process_005", &["process"]),
    ("process_008", &["end"]),
    ("process_009", &["process"]),
    ("process_013", &["is"]),
    ("protected_type_500", &["protected"]),
    ("protected_type_501", &["end"]),
    ("protected_type_502", &["protected"]),
    ("protected_type_body_500", &["protected"]),
    ("protected_type_body_501", &["body"]),
    ("protected_type_body_502", &["end"]),
    ("protected_type_body_503", &["protected"]),
    ("protected_type_body_504", &["body"]),
    ("range_001", &["downto"]),
    ("range_002", &["to"]),
    ("range_constraint_500", &["range"]),
    ("record_type_definition_500", &["record"]),
    ("record_type_definition_501", &["end"]),
    ("record_type_definition_502", &["record"]),
    ("report_statement_500", &["report"]),
    ("report_statement_501", &["severity"]),
    ("return_statement_500", &["return"]),
    ("selected_assignment_500", &["with"]),
    ("selected_assignment_501", &["select"]),
    ("selected_assignment_502", &["force"]),
    ("selected_assignment_503", &["when"]),
    ("shift_operator_500", &["sll", "srl", "sla", "sra", "rol", "ror"]),
    ("signal_002", &["signal"]),
    ("subprogram_instantiation_501", &["is"]),
    ("subprogram_instantiation_502", &["new"]),
    ("subprogram_kind_500", &["procedure"]),
    ("subprogram_kind_501", &["function"]),
    ("subtype_500", &["subtype"]),
    ("subtype_502", &["is"]),
    ("type_002", &["type"]),
    ("type_013", &["is"]),
    ("unbounded_array_definition_500", &["array"]),
    ("unbounded_array_definition_501", &["of"]),
    ("use_clause_503", &["all"]),
    ("variable_002", &["variable"]),
    ("variable_500", &["shared"]),
    ("wait_500", &["wait"]),
    ("wait_501", &["on"]),
    ("wait_502", &["until"]),
    ("wait_503", &["for"]),
}

#[cfg(test)]
mod tests {
    #[test]
    fn every_rule_prefix_is_mapped() {
        let unmapped: Vec<&str> = super::RULES
            .iter()
            .map(|(info, _)| info.id)
            .filter(|id| super::constructs(id).is_empty())
            .filter(|id| {
                !["logical_operator", "shift_operator", "subprogram_kind"]
                    .iter()
                    .any(|p| id.starts_with(p))
            })
            .collect();
        assert!(unmapped.is_empty(), "{unmapped:?}");
    }
}
