//! Waivers: findings a project has decided to accept, listed in a file with a reason.
//!
//! `-- vsg_off rule` suppresses a rule at a place in the source; a waiver does it from the
//! outside, which is what makes adopting a rule set on an existing codebase possible: run
//! `--generate_waivers waivers.yaml` once, pass `--waivers waivers.yaml` afterwards, and only
//! new violations are reported. Waived findings never affect the exit code.
//!
//! ```yaml
//! waivers:
//!   - rule: signal_008
//!     files: 'generated/**/*.vhd'
//!     lines: [12, 45]        # omit to waive the rule in the whole file
//!     reason: generated by hdl-registers
//! ```

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use yaml_serde::Value;

pub(crate) struct Waiver {
    /// Rule id, or `*` for every rule.
    rule: String,
    /// Glob against the file name as it is reported; `None` matches every file.
    files: Option<String>,
    /// Lines the waiver covers; empty covers the whole file.
    lines: Vec<usize>,
    pub(crate) reason: String,
}

#[derive(Default)]
pub(crate) struct Waivers(Vec<Waiver>);

fn normalize(name: &str) -> String {
    name.replace('\\', "/").trim_start_matches("./").to_owned()
}

impl Waivers {
    pub(crate) fn load(paths: &[PathBuf]) -> Result<Waivers, String> {
        let mut out = Vec::new();
        for path in paths {
            let text =
                std::fs::read_to_string(path).map_err(|e| format!("{}: {e}", path.display()))?;
            let doc: Value =
                yaml_serde::from_str(&text).map_err(|e| format!("{}: {e}", path.display()))?;
            let list = doc
                .as_mapping()
                .and_then(|m| m.get("waivers"))
                .and_then(Value::as_sequence)
                .ok_or_else(|| format!("{}: expected a `waivers` list", path.display()))?;
            for item in list {
                let map = item
                    .as_mapping()
                    .ok_or_else(|| format!("{}: each waiver must be a mapping", path.display()))?;
                let text = |key: &str| {
                    map.get(key)
                        .and_then(Value::as_str)
                        .map(str::trim)
                        .filter(|s| !s.is_empty())
                        .map(str::to_owned)
                };
                let rule = text("rule")
                    .ok_or_else(|| format!("{}: a waiver needs a `rule`", path.display()))?;
                let lines = map
                    .get("lines")
                    .and_then(Value::as_sequence)
                    .map(|s| {
                        s.iter()
                            .filter_map(Value::as_u64)
                            .filter_map(|n| usize::try_from(n).ok())
                            .collect()
                    })
                    .unwrap_or_default();
                out.push(Waiver {
                    rule,
                    files: text("files").as_deref().map(normalize),
                    lines,
                    reason: text("reason").unwrap_or_default(),
                });
            }
        }
        Ok(Waivers(out))
    }

    pub(crate) fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// The first waiver covering this finding, if any.
    pub(crate) fn waives(&self, file: &str, rule: &str, line: usize) -> Option<&Waiver> {
        let file = normalize(file);
        self.0.iter().find(|w| {
            (w.rule == rule || w.rule == "*")
                && w.files.as_ref().is_none_or(|pattern| {
                    vsg_rs::config::glob(pattern.as_bytes(), file.as_bytes())
                        // A bare file name in the waiver also matches that file reported with a
                        // longer path, which is what someone writing one by hand expects.
                        || Path::new(&file).ends_with(pattern)
                })
                && (w.lines.is_empty() || w.lines.contains(&line))
        })
    }
}

/// A waiver file covering exactly the findings given, as `(file, rule, line)`.
pub(crate) fn generate(findings: &[(String, String, usize)]) -> String {
    let mut grouped: BTreeMap<(&str, &str), Vec<usize>> = BTreeMap::new();
    for (file, rule, line) in findings {
        grouped
            .entry((file.as_str(), rule.as_str()))
            .or_default()
            .push(*line);
    }
    let mut out = String::from(
        "# Written by `vsg-rs --generate_waivers`. Each entry accepts the violations that exist\n\
         # today; delete `lines:` to waive the rule in the whole file, and replace the reason\n\
         # with why the code is allowed to stay this way.\nwaivers:\n",
    );
    for ((file, rule), mut lines) in grouped {
        lines.sort_unstable();
        lines.dedup();
        let lines: Vec<String> = lines.iter().map(usize::to_string).collect();
        let _ = write!(
            out,
            "  - rule: {rule}\n    files: '{}'\n    lines: [{}]\n    reason: TODO\n",
            normalize(file).replace('\'', "''"),
            lines.join(", ")
        );
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn waivers(yaml: &str) -> Waivers {
        let dir = tempfile::tempdir().expect("temporary directory");
        let path = dir.path().join("w.yaml");
        std::fs::write(&path, yaml).expect("write");
        Waivers::load(&[path]).expect("valid waiver file")
    }

    #[test]
    fn matches_rule_file_and_line() {
        let w = waivers(
            "waivers:\n  - rule: signal_008\n    files: 'src/**/*.vhd'\n    lines: [7]\n    reason: legacy\n",
        );
        assert!(w.waives("src/a/b.vhd", "signal_008", 7).is_some());
        assert!(w.waives("src/a/b.vhd", "signal_008", 8).is_none());
        assert!(w.waives("src/a/b.vhd", "signal_009", 7).is_none());
        assert!(w.waives("test/b.vhd", "signal_008", 7).is_none());
    }

    #[test]
    fn omitted_fields_widen_the_match() {
        let w = waivers("waivers:\n  - rule: '*'\n    reason: everything\n");
        assert!(w.waives("any/file.vhd", "whatever_001", 99).is_some());
        let w =
            waivers("waivers:\n  - rule: signal_008\n    files: b.vhd\n    reason: whole file\n");
        assert!(w.waives("src/b.vhd", "signal_008", 1).is_some());
        assert!(w.waives("src/b.vhd", "signal_008", 4000).is_some());
    }

    #[test]
    fn generated_waivers_cover_their_own_findings() {
        let findings = vec![
            ("src/a.vhd".to_owned(), "signal_008".to_owned(), 3),
            ("src/a.vhd".to_owned(), "signal_008".to_owned(), 1),
            ("src/b.vhd".to_owned(), "entity_019".to_owned(), 2),
        ];
        let w = waivers(&generate(&findings));
        for (file, rule, line) in &findings {
            assert!(
                w.waives(file, rule, *line).is_some(),
                "{file} {rule} {line}"
            );
        }
        assert!(w.waives("src/a.vhd", "signal_008", 2).is_none());
    }

    #[test]
    fn a_waiver_needs_a_rule() {
        let dir = tempfile::tempdir().expect("temporary directory");
        let path = dir.path().join("w.yaml");
        std::fs::write(&path, "waivers:\n  - reason: nothing\n").expect("write");
        assert!(Waivers::load(&[path]).is_err());
    }
}
